DROP TABLE IF EXISTS `t_coupon_template_0`;
CREATE TABLE `t_coupon_template_0` (
                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
                                       `coupon_template_id` bigint NOT NULL COMMENT '优惠券模板id',
                                       `name` varchar(256) DEFAULT NULL COMMENT '优惠券名称',
                                       `shop_number` bigint DEFAULT NULL COMMENT '店铺编号',
                                       `source` tinyint(1) DEFAULT NULL COMMENT '优惠券来源 0：店铺券 1：平台券',
                                       `target` tinyint(1) DEFAULT NULL COMMENT '优惠对象 0：商品专属 1：全店通用',
                                       `goods` varchar(64) DEFAULT NULL COMMENT '优惠商品编码',
                                       `type` tinyint(1) DEFAULT NULL COMMENT '优惠类型 0：立减券 1：满减券 2：折扣券',
                                       `valid_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
                                       `valid_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
                                       `stock` int DEFAULT NULL COMMENT '库存',
                                       `receive_rule` json DEFAULT NULL COMMENT '领取规则',
                                       `consume_rule` json DEFAULT NULL COMMENT '消耗规则',
                                       `status` tinyint(1) DEFAULT NULL COMMENT '优惠券状态 0：生效中 1：已结束',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识 0：未删除 1：已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `coupon_template_id` (`coupon_template_id`),
                                       KEY `idx_shop_number` (`shop_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='优惠券模板表';
DROP TABLE IF EXISTS `t_coupon_template_1`;
CREATE TABLE `t_coupon_template_1` (
                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
                                       `coupon_template_id` bigint NOT NULL COMMENT '优惠券模板id',
                                       `name` varchar(256) DEFAULT NULL COMMENT '优惠券名称',
                                       `shop_number` bigint DEFAULT NULL COMMENT '店铺编号',
                                       `source` tinyint(1) DEFAULT NULL COMMENT '优惠券来源 0：店铺券 1：平台券',
                                       `target` tinyint(1) DEFAULT NULL COMMENT '优惠对象 0：商品专属 1：全店通用',
                                       `goods` varchar(64) DEFAULT NULL COMMENT '优惠商品编码',
                                       `type` tinyint(1) DEFAULT NULL COMMENT '优惠类型 0：立减券 1：满减券 2：折扣券',
                                       `valid_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
                                       `valid_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
                                       `stock` int DEFAULT NULL COMMENT '库存',
                                       `receive_rule` json DEFAULT NULL COMMENT '领取规则',
                                       `consume_rule` json DEFAULT NULL COMMENT '消耗规则',
                                       `status` tinyint(1) DEFAULT NULL COMMENT '优惠券状态 0：生效中 1：已结束',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识 0：未删除 1：已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `coupon_template_id` (`coupon_template_id`),
                                       KEY `idx_shop_number` (`shop_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='优惠券模板表';
DROP TABLE IF EXISTS `t_coupon_template_2`;
CREATE TABLE `t_coupon_template_2` (
                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
                                       `coupon_template_id` bigint NOT NULL COMMENT '优惠券模板id',
                                       `name` varchar(256) DEFAULT NULL COMMENT '优惠券名称',
                                       `shop_number` bigint DEFAULT NULL COMMENT '店铺编号',
                                       `source` tinyint(1) DEFAULT NULL COMMENT '优惠券来源 0：店铺券 1：平台券',
                                       `target` tinyint(1) DEFAULT NULL COMMENT '优惠对象 0：商品专属 1：全店通用',
                                       `goods` varchar(64) DEFAULT NULL COMMENT '优惠商品编码',
                                       `type` tinyint(1) DEFAULT NULL COMMENT '优惠类型 0：立减券 1：满减券 2：折扣券',
                                       `valid_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
                                       `valid_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
                                       `stock` int DEFAULT NULL COMMENT '库存',
                                       `receive_rule` json DEFAULT NULL COMMENT '领取规则',
                                       `consume_rule` json DEFAULT NULL COMMENT '消耗规则',
                                       `status` tinyint(1) DEFAULT NULL COMMENT '优惠券状态 0：生效中 1：已结束',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识 0：未删除 1：已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `coupon_template_id` (`coupon_template_id`),
                                       KEY `idx_shop_number` (`shop_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='优惠券模板表';
DROP TABLE IF EXISTS `t_coupon_template_3`;
CREATE TABLE `t_coupon_template_3` (
                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
                                       `coupon_template_id` bigint NOT NULL COMMENT '优惠券模板id',
                                       `name` varchar(256) DEFAULT NULL COMMENT '优惠券名称',
                                       `shop_number` bigint DEFAULT NULL COMMENT '店铺编号',
                                       `source` tinyint(1) DEFAULT NULL COMMENT '优惠券来源 0：店铺券 1：平台券',
                                       `target` tinyint(1) DEFAULT NULL COMMENT '优惠对象 0：商品专属 1：全店通用',
                                       `goods` varchar(64) DEFAULT NULL COMMENT '优惠商品编码',
                                       `type` tinyint(1) DEFAULT NULL COMMENT '优惠类型 0：立减券 1：满减券 2：折扣券',
                                       `valid_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
                                       `valid_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
                                       `stock` int DEFAULT NULL COMMENT '库存',
                                       `receive_rule` json DEFAULT NULL COMMENT '领取规则',
                                       `consume_rule` json DEFAULT NULL COMMENT '消耗规则',
                                       `status` tinyint(1) DEFAULT NULL COMMENT '优惠券状态 0：生效中 1：已结束',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识 0：未删除 1：已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `coupon_template_id` (`coupon_template_id`),
                                       KEY `idx_shop_number` (`shop_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='优惠券模板表';
DROP TABLE IF EXISTS `t_coupon_template_4`;
CREATE TABLE `t_coupon_template_4` (
                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
                                       `coupon_template_id` bigint NOT NULL COMMENT '优惠券模板id',
                                       `name` varchar(256) DEFAULT NULL COMMENT '优惠券名称',
                                       `shop_number` bigint DEFAULT NULL COMMENT '店铺编号',
                                       `source` tinyint(1) DEFAULT NULL COMMENT '优惠券来源 0：店铺券 1：平台券',
                                       `target` tinyint(1) DEFAULT NULL COMMENT '优惠对象 0：商品专属 1：全店通用',
                                       `goods` varchar(64) DEFAULT NULL COMMENT '优惠商品编码',
                                       `type` tinyint(1) DEFAULT NULL COMMENT '优惠类型 0：立减券 1：满减券 2：折扣券',
                                       `valid_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
                                       `valid_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
                                       `stock` int DEFAULT NULL COMMENT '库存',
                                       `receive_rule` json DEFAULT NULL COMMENT '领取规则',
                                       `consume_rule` json DEFAULT NULL COMMENT '消耗规则',
                                       `status` tinyint(1) DEFAULT NULL COMMENT '优惠券状态 0：生效中 1：已结束',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识 0：未删除 1：已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `coupon_template_id` (`coupon_template_id`),
                                       KEY `idx_shop_number` (`shop_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='优惠券模板表';
DROP TABLE IF EXISTS `t_coupon_template_5`;
CREATE TABLE `t_coupon_template_5` (
                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
                                       `coupon_template_id` bigint NOT NULL COMMENT '优惠券模板id',
                                       `name` varchar(256) DEFAULT NULL COMMENT '优惠券名称',
                                       `shop_number` bigint DEFAULT NULL COMMENT '店铺编号',
                                       `source` tinyint(1) DEFAULT NULL COMMENT '优惠券来源 0：店铺券 1：平台券',
                                       `target` tinyint(1) DEFAULT NULL COMMENT '优惠对象 0：商品专属 1：全店通用',
                                       `goods` varchar(64) DEFAULT NULL COMMENT '优惠商品编码',
                                       `type` tinyint(1) DEFAULT NULL COMMENT '优惠类型 0：立减券 1：满减券 2：折扣券',
                                       `valid_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
                                       `valid_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
                                       `stock` int DEFAULT NULL COMMENT '库存',
                                       `receive_rule` json DEFAULT NULL COMMENT '领取规则',
                                       `consume_rule` json DEFAULT NULL COMMENT '消耗规则',
                                       `status` tinyint(1) DEFAULT NULL COMMENT '优惠券状态 0：生效中 1：已结束',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识 0：未删除 1：已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `coupon_template_id` (`coupon_template_id`),
                                       KEY `idx_shop_number` (`shop_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='优惠券模板表';
DROP TABLE IF EXISTS `t_coupon_template_6`;
CREATE TABLE `t_coupon_template_6` (
                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
                                       `coupon_template_id` bigint NOT NULL COMMENT '优惠券模板id',
                                       `name` varchar(256) DEFAULT NULL COMMENT '优惠券名称',
                                       `shop_number` bigint DEFAULT NULL COMMENT '店铺编号',
                                       `source` tinyint(1) DEFAULT NULL COMMENT '优惠券来源 0：店铺券 1：平台券',
                                       `target` tinyint(1) DEFAULT NULL COMMENT '优惠对象 0：商品专属 1：全店通用',
                                       `goods` varchar(64) DEFAULT NULL COMMENT '优惠商品编码',
                                       `type` tinyint(1) DEFAULT NULL COMMENT '优惠类型 0：立减券 1：满减券 2：折扣券',
                                       `valid_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
                                       `valid_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
                                       `stock` int DEFAULT NULL COMMENT '库存',
                                       `receive_rule` json DEFAULT NULL COMMENT '领取规则',
                                       `consume_rule` json DEFAULT NULL COMMENT '消耗规则',
                                       `status` tinyint(1) DEFAULT NULL COMMENT '优惠券状态 0：生效中 1：已结束',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识 0：未删除 1：已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `coupon_template_id` (`coupon_template_id`),
                                       KEY `idx_shop_number` (`shop_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='优惠券模板表';
DROP TABLE IF EXISTS `t_coupon_template_7`;
CREATE TABLE `t_coupon_template_7` (
                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
                                       `coupon_template_id` bigint NOT NULL COMMENT '优惠券模板id',
                                       `name` varchar(256) DEFAULT NULL COMMENT '优惠券名称',
                                       `shop_number` bigint DEFAULT NULL COMMENT '店铺编号',
                                       `source` tinyint(1) DEFAULT NULL COMMENT '优惠券来源 0：店铺券 1：平台券',
                                       `target` tinyint(1) DEFAULT NULL COMMENT '优惠对象 0：商品专属 1：全店通用',
                                       `goods` varchar(64) DEFAULT NULL COMMENT '优惠商品编码',
                                       `type` tinyint(1) DEFAULT NULL COMMENT '优惠类型 0：立减券 1：满减券 2：折扣券',
                                       `valid_start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
                                       `valid_end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
                                       `stock` int DEFAULT NULL COMMENT '库存',
                                       `receive_rule` json DEFAULT NULL COMMENT '领取规则',
                                       `consume_rule` json DEFAULT NULL COMMENT '消耗规则',
                                       `status` tinyint(1) DEFAULT NULL COMMENT '优惠券状态 0：生效中 1：已结束',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `del_flag` tinyint(1) DEFAULT NULL COMMENT '删除标识 0：未删除 1：已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `coupon_template_id` (`coupon_template_id`),
                                       KEY `idx_shop_number` (`shop_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='优惠券模板表';
